### ISSUE TITLE
RNG state is initialized to zero, rng.fill doesn't work

### ISSUE THREAD

**Issue by scorpiolin** [vinograd47/AdaptiveManifoldFilter#1]
hi, I found that dst image  is all black , what's wrong with it?

**Comment by vinograd47** [comment]
Hello. Could you attach your image?

**Comment by scorpiolin** [comment]
hi, the attachment is the output of program . thanks :)

![test](https://f.cloud.github.com/assets/1722021/833371/9f555e32-f29e-11e2-9faa-3bb090d17f64.jpg)
![output](https://f.cloud.github.com/assets/1722021/833372/9f5455d2-f29e-11e2-9e25-0ae0d545408d.png)

**Comment by vinograd47** [comment]
I updated the code. Please pull last changes and check on your image.

**Comment by scorpiolin** [comment]
thank you ~~

**Comment by vinograd47** [comment]
Solved

**Comment by scorpiolin** [comment]
hi, I tested about 500 images, almost 70 images have the same problem.

**Comment by scorpiolin** [comment]
![aaron_sorkin_0002](https://f.cloud.github.com/assets/1722021/843112/097cb908-f3b8-11e2-9aa9-ca11b4bbd447.jpg)
![aaron_peirsol_0003](https://f.cloud.github.com/assets/1722021/843113/098000c2-f3b8-11e2-86d9-5b55b342fb32.jpg)
![al_davis_0002](https://f.cloud.github.com/assets/1722021/843114/0984e75e-f3b8-11e2-84cd-c856a7ad8dfd.jpg)

they are some samples that output all black. I think the bug is not fixed completely.
