### ISSUE TITLE
Division by zero, manifolds are filled with NANs

### ISSUE THREAD

**Issue by scorpiolin** [vinograd47/AdaptiveManifoldFilter#2]
hi, I tested about 500 images, almost 70 images have the same problem.

**Comment by vinograd47** [comment]
There was another bug (division by zero). I fixed it. Try new code.

**Comment by vinograd47** [comment]
Fixed in https://github.com/jet47/AdaptiveManifoldFilter/commit/0c94f9adad14f5dd595d4a04156628a8936a24b2
